// Generated by CoffeeScript 1.4.0

/*
Sticky Elements Shortcut for jQuery Waypoints - v2.0.2
Copyright (c) 2011-2013 Caleb Troughton
Dual licensed under the MIT license and GPL license.
https://github.com/imakewebthings/jquery-waypoints/blob/master/licenses.txt
*/

(function() {
  
  (function(root, factory) {
    if (typeof define === 'function' && define.amd) {
      return define(['jquery', 'waypoints'], factory);
    } else {
      return factory(root.jQuery);
    }
  })(this, function($) {
    var defaults, wrap;
    defaults = {
      wrapper: '<div class="sticky-wrapper" />',
      stuckClass: 'stuck in',
      stopSticky: '.stick-stop',
      setWidth: true
    };
    wrap = function($elements, options) {
      $elements.wrap(options.wrapper);
      $elements.each(function() {
        var $this = $(this);

        $this.parent().height($this.outerHeight());

        if(options.setWidth){ $this.width($this.outerWidth()); }

        if(options.offset){ $this.css('top', options.offset); }

      });
      return $elements.parent();
    };   
    return $.waypoints('extendFn', 'sticky', function(options) {
      var $wrap, originalHandler, $sticky = $(this);
      options = $.extend({}, $.fn.waypoint.defaults, defaults, options);
      $wrap = wrap(this, options);
      originalHandler = options.handler;
      options.handler = function(direction) {
        var shouldBeStuck;
        shouldBeStuck = direction === 'down' || direction === 'right';
        $sticky.toggleClass(options.stuckClass, shouldBeStuck);
        if (originalHandler != null) {
          return originalHandler.call(this, direction);
        }
      };


      $(options.stopSticky).waypoint({
        offset: function() {
          return $sticky.height() + 45;
        },
        handler: function(direction) {
          var $this = $(this)
          if(direction === 'down' || direction === 'right'){
            console.log("After stopSticky")
            console.log($this.position())
            console.log(options.offset)
            console.log($sticky.height())
            $sticky.removeClass("stuck")
            if($sticky.hasClass("sticky-sidebar") && $this.position() !== undefined){
              $sticky.css({
                "top": parseInt($this.position().top) - $sticky.height() + "px",
                "position": "absolute"
              })
            }            
          }else{
            $sticky.addClass("stuck")
            if($sticky.hasClass("sticky-sidebar")){
              $sticky.css({
                "top": options.offset,
                "position": ""
              })
            }
          }
        }
      })

      $wrap.waypoint(options);
      return this;
    });
  });

}).call(this);
